# coding=utf-8
# Título: Wood
# Descripción: Autocompletamiento de tablas y campos del DAL.
# Autor: José Antonio Pérez López
# Versión: 1

def generate_aliases(db, name, request):
    from gluon.fileutils import write_file
    import os

    current_folder = request.folder
    file_path = os.path.join(current_folder, "models/wood/{}_aliases.py".format(name))
    tables_names = db.tables

    lines = '''# coding=utf-8
# Autocomplete helpers for DAL tables and fields.
# Generated by wood.py
# Please do not modify this module manually.

if 0:
    from gluon.dal.base import DAL, Table, Field
    from gluon.dal.objects import Rows

    class db(DAL):
'''
    for table_name in tables_names:
        lines += """
        # Table: '{0}'
        class {0}(Table):""".format(table_name)
        for field in db[table_name].fields:
            lines += "\n            {} = Field()".format(field)
        lines += "\n\n        {0} = {0}\n".format(table_name)
    lines += "\n\n        def select(orderby=None, groupby=None, limitby=None, distinct=False, left=None, cache=None, *columns): return Rows()\n"
    lines += "\n\n        def count(distinct=False): return Rows()\n"
    lines += "\n    db = db"

    write_file(file_path, lines)